code --install-extension kube.42header
code --install-extension alexiv.vscode-angular2-files
code --install-extension Angular.ng-template
code --install-extension mrmlnc.vscode-apache
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension joshpeng.sublime-babel-vscode
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension t-sauer.vscode-babel-repl
code --install-extension austin.code-gnu-global
code --install-extension mitaki28.vscode-clang
code --install-extension ms-vscode.cpptools
code --install-extension bradlc.vscode-tailwindcss
code --install-extension shinnn.stylelint
code --install-extension ecmel.vscode-html-css
code --install-extension mechatroner.rainbow-csv
code --install-extension CoenraadS.disableligatures
code --install-extension EditorConfig.EditorConfig
code --install-extension lihui.vs-color-picker
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension patbenatar.advanced-new-file
code --install-extension sohamkamani.code-eol
code --install-extension ritwickdey.LiveServer
code --install-extension tomoki1207.selectline-statusbar
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension YoshinoriN.current-file-path
code --install-extension mikestead.dotenv
code --install-extension codezombiech.gitignore
code --install-extension eamodio.gitlens
code --install-extension KnisterPeter.vscode-github
code --install-extension abusaidm.html-snippets
code --install-extension ginfuru.ginfuru-vscode-jekyll-syntax
code --install-extension ginfuru.vscode-jekyll-snippets
code --install-extension dbaeumer.vscode-eslint
code --install-extension jeremyrajan.webpack
code --install-extension TwentyChung.jsx
code --install-extension xabikos.JavaScriptSnippets
code --install-extension HookyQR.beautify
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension yzhang.markdown-all-in-one
code --install-extension odubuc.mysql-inline-decorator
code --install-extension christian-kohler.npm-intellisense
code --install-extension eg2.vscode-npm-script
code --install-extension jasonnutter.search-node-modules
code --install-extension leizongmin.node-module-intellisense
code --install-extension waderyan.nodejs-extension-pack
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension Sophisticode.php-formatter
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension lukazakrajsek.react-utils
code --install-extension taichi.react-beautify
code --install-extension ritwickdey.live-sass
code --install-extension robinbentley.sass-indented
code --install-extension spook.easysass
code --install-extension jock.svg
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension hollowtree.vue-snippets
code --install-extension jcbuisson.vue
code --install-extension octref.vetur
