code --uninstall-extension HookyQR.beautify
code --uninstall-extension KnisterPeter.vscode-github
code --uninstall-extension Sophisticode.php-formatter
code --uninstall-extension YoshinoriN.current-file-path
code --uninstall-extension abusaidm.html-snippets
code --uninstall-extension alexiv.vscode-angular2-files
code --uninstall-extension Angular.ng-template
code --uninstall-extension austin.code-gnu-global
code --uninstall-extension bmewburn.vscode-intelephense-client
code --uninstall-extension bradlc.vscode-tailwindcss
code --uninstall-extension christian-kohler.npm-intellisense
code --uninstall-extension christian-kohler.path-intellisense
code --uninstall-extension codezombiech.gitignore
code --uninstall-extension CoenraadS.disableligatures
code --uninstall-extension DavidAnson.vscode-markdownlint
code --uninstall-extension dbaeumer.vscode-eslint
code --uninstall-extension dzannotti.vscode-babel-coloring
code --uninstall-extension eamodio.gitlens
code --uninstall-extension ecmel.vscode-html-css
code --uninstall-extension EditorConfig.EditorConfig
code --uninstall-extension eg2.vscode-npm-script
code --uninstall-extension felixfbecker.php-debug
code --uninstall-extension felixfbecker.php-intellisense
code --uninstall-extension felixfbecker.php-pack
code --uninstall-extension ginfuru.ginfuru-vscode-jekyll-syntax
code --uninstall-extension ginfuru.vscode-jekyll-snippets
code --uninstall-extension hollowtree.vue-snippets
code --uninstall-extension jasonnutter.search-node-modules
code --uninstall-extension jcbuisson.vue
code --uninstall-extension jeremyrajan.webpack
code --uninstall-extension jock.svg
code --uninstall-extension kube.42header
code --uninstall-extension kumar-harsh.graphql-for-vscode
code --uninstall-extension leizongmin.node-module-intellisense
code --uninstall-extension lihui.vs-color-picker
code --uninstall-extension lukazakrajsek.react-utils
code --uninstall-extension mechatroner.rainbow-csv
code --uninstall-extension mgmcdermott.vscode-language-babel
code --uninstall-extension mikestead.dotenv
code --uninstall-extension mitaki28.vscode-clang
code --uninstall-extension mrmlnc.vscode-apache
code --uninstall-extension ms-vscode.cpptools
code --uninstall-extension ms-vscode.vscode-typescript-tslint-plugin
code --uninstall-extension msjsdiag.debugger-for-chrome
code --uninstall-extension octref.vetur
code --uninstall-extension odubuc.mysql-inline-decorator
code --uninstall-extension onecentlin.laravel5-snippets
code --uninstall-extension patbenatar.advanced-new-file
code --uninstall-extension ritwickdey.live-sass
code --uninstall-extension ritwickdey.LiveServer
code --uninstall-extension sohamkamani.code-eol
code --uninstall-extension spook.easysass
code --uninstall-extension t-sauer.vscode-babel-repl
code --uninstall-extension tomoki1207.selectline-statusbar
code --uninstall-extension vscode-icons-team.vscode-icons
code --uninstall-extension waderyan.nodejs-extension-pack
code --uninstall-extension wayou.vscode-todo-highlight
code --uninstall-extension xabikos.JavaScriptSnippets
code --uninstall-extension yzhang.markdown-all-in-one
